### ISSUE TITLE
Display more information on mouse hover.

### ISSUE THREAD

**Issue by theixdev** [SSWConsulting/SSW.Rules.Widget#14]
CC:  @adamcogan  @theixdev @tiagov8 
When hovering a mouse over a rule in the widget,  display when the rule was last updated.

**Comment by tiagov8** [comment]
Hi @theixdev ,

Please try the 'bottom' version of https://www.w3schools.com/css/css_tooltip.asp

**Comment by jaydenalchin** [comment]
Hi @theixdev 

As per our conversation, this tooltip is redundant since the widget itself already clearly displays this information.

![image](https://user-images.githubusercontent.com/75593567/142092055-25ddcb5e-59c0-452d-a3cb-b3fd49590b4b.png)
**Figure: Time since last update already on rules widget**

1. Please close this issue if you agree. 

-Jayden
